# Generated by Django 3.2.6 on 2021-08-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlsStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField()),
                ('url_full', models.URLField(max_length=500)),
                ('url_short', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deletable', models.BooleanField(default=True)),
            ],
        ),
    ]
