# Generated by Django 3.2.6 on 2021-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsstorage',
            name='counter',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
